name: Push components to IDF Component Registry

on:
  push:
    branches:
      - main

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Upload components to IDF Component Registry
        uses: espressif/upload-components-ci-action@v1
        with:
          directories: esp_flash_nor;
          namespace: "espressif"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
