name: Push components to Espressif Component Service

# Copy from https://github.com/espressif/idf-extra-components/blob/master/.github/workflows/upload_component.yml

on:
  # For pull requests: perform upload with "--dry-run" argument,
  # i.e. validate that the component passes all checks for being uploaded.
  pull_request:

  push:
    branches:
      - main

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - run: |
          echo "${{ ( github.ref_name != 'main' || github.repository_owner != 'espressif' ) && 'Checking' || 'Uploading' }} components"
      - name: Upload components to component service
        uses: espressif/upload-components-ci-action@v1
        with:
          # Please try to keep the directories list sorted.
          #
          # Do note, however, that if you are updating two components in the same PR
          # and one depends on the other, the new version of the 2nd component won't
          # be found in the registry when the 1st component is uploaded.
          #
          # This is only a problem if you are adding two components for the first time,
          # or if the 2nd component depends on the exact (new) version of the first one.
          #
          directories: >
            esp_flash_nor;
          namespace: "espressif"
          # API token will only be available in the main branch in the main repository.
          # However, dry-run doesn't require a valid token.
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
          dry_run: ${{ github.ref_name != 'main' || github.repository_owner != 'espressif' }}
